name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Verify hello action works
        # action.ymlが存在するディレクトリへの相対パス
        uses: ./
