# This is a basic workflow to help you get started with Actions
name: Uppercase

on:
  push:
    # pushした時に起動するんだけど、masterの時は無視する設定
    branches-ignore:
      - master
jobs:
  prComment:
    runs-on: ubuntu-latest
    steps:
      - id: uppercase
        uses: itoaki/action-uppercase@v1.0.0
        with:
          text: Hello, World! will may be uppercase!!
      - name: Print converted text
        run: echo "${{ steps.uppercase.outputs.uppercase-text }}"
